// <auto-generated />
namespace ECS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LinkedIn_Expired_Flag_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkedIn_Expired_Flag_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201803132236171_LinkedIn_Expired_Flag_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
