// <auto-generated />
namespace ECS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LinkedIn_Table_Reintroduced : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkedIn_Table_Reintroduced));
        
        string IMigrationMetadata.Id
        {
            get { return "201803212034306_LinkedIn_Table_Reintroduced"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
