// <auto-generated />
namespace ECS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DateTime_Added_To_JAccessToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTime_Added_To_JAccessToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201803220610284_DateTime_Added_To_JAccessToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
