// <auto-generated />
namespace ECS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LinkedIn_TokenId_Added_and_Removed_Value_as_Key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkedIn_TokenId_Added_and_Removed_Value_as_Key));
        
        string IMigrationMetadata.Id
        {
            get { return "201803140805086_LinkedIn_TokenId_Added_and_Removed_Value_as_Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
