// <auto-generated />
namespace ECS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Account_Changes_to_Store_Hashed_Password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Account_Changes_to_Store_Hashed_Password));
        
        string IMigrationMetadata.Id
        {
            get { return "201803182040532_Account_Changes_to_Store_Hashed_Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
